### ISSUE TITLE
[Bug]: Undefined variable $getGallery using Lightbox::make()

### ISSUE THREAD

**Issue by lutek** [njxqlus/filament-lightbox#10]
### What happened?

Got ErrorException:

`Undefined variable $getGallery`

### How to reproduce the bug

just put this into infolist schema definition
```
use Njxqlus\Filament\Components\Infolists\Lightbox;
 
Lightbox::make()
    ->schema([
        Components\TextEntry::make('year'),
    ])
    ->href('https://biati-digital.github.io/glightbox/demo/img/large/gm2.jpg')
```

### Package Version

2.1

### PHP Version

8.2

### Laravel Version

10.46

### Filament Version

3.2.42

**Comment by njxqlus** [comment]
Fixed in [3.0.0](https://github.com/njxqlus/filament-lightbox/releases/tag/3.0.0)
