### ISSUE TITLE
Setting label to null shows Spatie's media uuid

### ISSUE THREAD

**Issue by buzkall** [njxqlus/filament-lightbox#5]
### What happened?

After updating to 2.1.1, the uuid of the spatie media has begun to appear above the image.

Should hiddenLabel() be used instead?

### How to reproduce the bug

Update to version 2.1.1 and use LightboxSpatieMediaLibraryImageEntry

### Package Version

2.1.1

### PHP Version

8.2

### Laravel Version

10.35

### Filament Version

3.1

**Comment by njxqlus** [comment]
Fixed in https://github.com/njxqlus/filament-lightbox/commit/420549a4cf9b3241ffa858a8f53f9a970a60edc6
