### ISSUE TITLE
I got error ->gallery() does not exist

### ISSUE THREAD

**Issue by davidtim** [njxqlus/filament-lightbox#8]
### What happened?

I got error Method Njxqlus\Filament\Components\Infolists\LightboxImageEntry::gallery does not exist.

### How to reproduce the bug

```
LightboxImageEntry::make('id_photo')
    ->href(fn (?string $state): ?string => asset('storage/'.$state))
    ->gallery(fn ($record): string => $record->english_name),
```

### Package Version

2.1

### PHP Version

8.2

### Laravel Version

10.41.0 

### Filament Version

3.2

**Comment by njxqlus** [comment]
Thank you for mentioning it. I forgot to update the documentation. The method you looking for now is called `slideGallery()`
