### ISSUE TITLE
[Bug]: LightboxSpatieMediaLibraryImageEntry overflow not appearing correctly

### ISSUE THREAD

**Issue by msalehipro** [njxqlus/filament-lightbox#9]
### What happened?

I expected to see overflow of images bottom of first row.

### How to reproduce the bug

When the count of images became so much, the overflow of thumbnails does not appearing correctly.
I'm not sure about LTR mode, i'm working in RTL mode.
here is a screenshot:
![image](https://github.com/njxqlus/filament-lightbox/assets/5165298/392d700f-1331-49ec-8cb3-1a95f3502918)

### Package Version

2.1.2

### PHP Version

8.1

### Laravel Version

10

### Filament Version

3.2

**Comment by njxqlus** [comment]
Fixed in [3.0.1](https://github.com/njxqlus/filament-lightbox/releases/tag/3.0.1)
